version: '3'
services:
  ginserver:
    build: 
      context: .
      dockerfile: gin.Dockerfile  
    ports:
      - "8080:8080"
  httpserver:
    build: 
      context: .
      dockerfile: http.Dockerfile
    ports:
      - "8000:8000"
