apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Values.name}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.internal}}
      targetPort: {{ .Values.ports.internal}}
      nodePort: {{ .Values.ports.node}}