name: gotest
on:
    push:
    pull_request:
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5

            - name: Build GIN server
              run: 	go build -o bin/ginserver ./cmd/gin_server/main.go
            
            - name: Build HTTP server
              run: 	go build -o bin/httpserver ./cmd/http_server/main.go
    
    golangci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5

            - name: Format
              run: go fmt ./...

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.60

    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5

            - name: Test
              run: go test ./...